### ISSUE TITLE
RequestInfo - array to string conversion

### ISSUE THREAD

**Issue by dododedodonl** [StydeNet/enlighten#11]
When in a test, a request is done using `$this->postJson($route, $data)`, it is possible (and valid) that `$data` contains a multi dimensional array:

```php
$this->postJson(route('routeName'), [
   'key1' => 'value1',
   'key2' => [
        'key3' => [
            1,
            3,
        ],
    ],
]);
```

This will result in the following exception when trying to view the generated enlighten data for the test (`enlighten/run/1/api/1`), triggered by the `implode`:
```
Array to string conversion at vendor/styde/enlighten/src/View/Components/RequestInputTableComponent.php:21)
```

**Comment by jeffochoa** [comment]
Ready to go on the next release: https://github.com/StydeNet/enlighten/commit/6c54aad5ee19729d562fa17279cee96cc8f333ea

@dododedodonl you can use the `main` branch in the meanwhile.
