### ISSUE TITLE
Feature: group by route

### ISSUE THREAD

**Issue by dododedodonl** [StydeNet/enlighten#13]
It would be great if it would also be possible to have a dashboard that groups the results by route instead of suite and test, so one could easily see all possible requests to a single route.

**Comment by sileence** [comment]
@dododedodonl we won't work on this for now; but we are happy to accept contributions for this feature.

**Comment by sileence** [comment]
@dododedodonl this is now available in 0.5.* as a new view called "endpoints", thanks for the suggestion!
