### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by simao-coutinho** [StydeNet/enlighten#19]
Good morning. it's possible to add a sample project to clear all the doubts that i have. Thanks

**Comment by sileence** [comment]
@BanenoLuso Hi! We've been very busy working in the next release of Enlighten. Of course we're planning sample projects and a demo for release 0.3 or 0.4 (we're currently at 0.2). In the meantime I invite you to install the package in a local project you're working on, it shouldn't take you more than 15 minutes to see the results.

**Comment by simao-coutinho** [comment]
I already installed but maybe i'm doing something wrong, the methods not appearing.
link: https://sportsstats.eu/enlighten/intro

**Comment by sileence** [comment]
@BanenoLuso Enlighten only creates info when you run your tests. In this case, you'd need to run the tests there. Alternatively (although we haven't used it in this way), run the tests in your local environment and upload the Enlighten DB data to the server.

In a future release we'll give you the possibility to export the docs as static files. But we haven't added that feature yet.

**Comment by simao-coutinho** [comment]
Can you post a Test Example code? thanks

**Comment by fajartaufik** [comment]
I got this error when trying to install
Package styde/enlighten at version  has a PHP requirement incompatible with your PHP version (7.3.0)

**Comment by fajartaufik** [comment]
I got this error **syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'**

public function addGroups(Collection $groups) : self
    {
        return $this
            ->each(function ($module) use (&$groups) {
                [$matches, $groups] = $groups->partition(fn($group) => $group->matches($module));  //error in this line
                $module->addGroups($matches);
            })
            ->addRemainingGroupsToTheDefaultModule($groups);
    }

**Comment by sileence** [comment]
@fajartaufik What PHP version you're using?

**Comment by sileence** [comment]
@BanenoLuso Any Test should work as an Example. Enlighten does not require any special annotation in order to work, you just need to follow our installation instructions to `Enlighten` your tests.

You can also check our tests/Integration folder for different usage example if you need more inspiration.

We will add more documentation after the release of 0.3.

**Comment by fajartaufik** [comment]
> @fajartaufik What PHP version you're using?

Im using PHP 7.3.0 and laravel 8

**Comment by sileence** [comment]
@fajartaufik at the moment we only support PHP 7.4 onwards. We could change that if enough people ask for PHP 7.3.

**Comment by sileence** [comment]
@fajartaufik Enlighten 0.3.2 comes with support for PHP 7.3 and even Laravel 7, please upgrade and try again: 

https://github.com/StydeNet/enlighten/blob/main/CHANGELOG.md

**Comment by fajartaufik** [comment]
> @fajartaufik Enlighten 0.3.2 comes with support for PHP 7.3 and even Laravel 7, please upgrade and try again:
> 
> https://github.com/StydeNet/enlighten/blob/main/CHANGELOG.md

Perfect, thank you @sileence

**Comment by sileence** [comment]
@BanenoLuso @fajartaufik You can try Enlighten here:

https://github.com/StydeNet/curso-de-laravel-desde-cero/tree/enlighten

Please follow the instructions in the readme.
