### ISSUE TITLE
followingRedirect can not record first reponse

### ISSUE THREAD

**Issue by smartymoon** [StydeNet/enlighten#35]
**Describe the bug**

i want to record redirect request after 302. there are an exception happend.
``` php
$this->actingAs($this->user)->followingRedirects()->put('reset_password', [
            'XDEBUG_SESSION_START' => 19226,
            'origin_password' => '654321',
            'password_confirmation' => '123456',
            'password' => '123456'
        ]);

```

making some change in HttpExampleCreatorMiddleware
``` php
 public function terminate($request, $response)
    {
        if ($response instanceof TestResponse) {
            $response = $response->baseResponse;
        }
        $this->httpExampleCreator->saveHttpResponseData($request, $response);
    }
```
i got that
```
Error : Call to a member function update() on null
 /Users/lee/Code/Sites/support/trump/vendor/styde/enlighten/src/TestExample.php:132
```
after three 3 hours study of code and watching 2020 US election

I give up

**To Reproduce**
make a 302 request in test and add followingRedirects method

**Expected behavior**
record two reqest completly

**Screenshots**
![截屏2020-11-04 下午5 34 15](https://user-images.githubusercontent.com/12489528/98094226-f7d01f80-1ec3-11eb-9ea1-8e94c7af5076.png)

**Additional context**
I love this package

**Comment by sileence** [comment]
@smartymoon hello! I have no tried Enlighten with the following redirect option, I'll do that as soon as I can and will let you know how it goes and if I can reproduce & fix the issue.

**Comment by sileence** [comment]
@smartymoon the fix is already in `dev` and will be deployed soon. Thanks for reporting the issue :)

**Comment by sileence** [comment]
@smartymoon deployed in 0.4.

**Comment by smartymoon** [comment]
@sileence  It is me who should say thank you. thank you for this package, thank you for fix this.   this package help me a lot

**Comment by sileence** [comment]
You’re welcome, @XinBa

Is this behavior ok? I was just thinking I should follow all the redirects
but show only the first request and the last response. What do you think?

**Comment by sileence** [comment]
@smartymoon we just pushed a new patch release (`0.4.1`) it improves this behaviour by saving all the requests with their corresponding responses

request 1 -> response 1
request 2 -> response 2
request 3 -> response 3

From 0.5.0 you'll be able to see if a request/response is following the redirect from a previous request/response.

**Comment by smartymoon** [comment]
@sileence  I have try dev branch, it works, thank you

**Comment by sileence** [comment]
@smartymoon great! you can also start using ^0.4 if you want :)
