### ISSUE TITLE
Unknown column 'order_num' into 'enlighten_example_groups'

### ISSUE THREAD

**Issue by ianfortier** [StydeNet/enlighten#39]
**Describe the bug**

` SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_num' in 'field list' (SQL: insert into `enlighten_example_groups` (`title`, `description`, `area`, `slug`, `order_num`, `run_id`, `class_name`, `updated_at`, `created_at`) values (xxxxxxxxxxxxxx, ?, unit, xxxxxxx, 9999, 1, Tests\Unit\XXXXXXX, 2020-11-15 19:21:51, 2020-11-15 19:21:51))`

**Additional context**
After upgrading from 0.3.6 to 0.5.2
I rerun the install and republish / fresh the migrations.

**Comment by ianfortier** [comment]
Solved by replacing the config.php file by the new version!

**Comment by jeffochoa** [comment]
Hi @ianfortier,

Please follow the instructions described on the changelog file to upgrade to the latest version https://github.com/StydeNet/enlighten/blob/main/CHANGELOG.md

It looks like you are using the old migrations file.

Try the following:

1. Remove all the files in `database/migrations/enlighten`
2. Publish the migrations files again with `php artisan vendor:publish --tag=enlighten-migrations`
3. Run the migrations with `php artisan enlighten:migrate:fresh`

Run the tests again.

Cheers,
Jeff.
