### ISSUE TITLE
Missing file parameter

### ISSUE THREAD

**Issue by dhtmdgkr123** [StydeNet/enlighten#46]
**Describe the bug**
run test code and generate document but file pararmeter is missing

**To Reproduce**
1. php artisan enlighten:migrate:fresh
2. php artisan test
3. php artisan enlighten:export

**Expected behavior**
Want fileparameter to document
my test code append file but file parameter content not found

```php
$requestUrl = route('updateTeamLogo', [
    'teamSlug' => $team->slug,
]);
$tryUpdateLogo = $this->postJson($requestUrl, [
    'logo_image' => UploadedFile::fake()->create('test.png', 2000),
])->assertOk();
```

**Screenshots**
![image](https://user-images.githubusercontent.com/27611405/103118759-a833f600-46b3-11eb-92fa-2799430f4962.png)

**Comment by sileence** [comment]
@dhtmdgkr123 hello! I just finished this fix/feature, you'll find it in `dev` for now, although we'll be re-deploying soon. You need to re-run the migrations or add a new "request_files" field to the example_requests table.

I hope this helps.

**Comment by dhtmdgkr123** [comment]
> @dhtmdgkr123 hello! I just finished this fix/feature, you'll find it in `dev` for now, although we'll be re-deploying soon. You need to re-run the migrations or add a new "request_files" field to the example_requests table.
> 
> I hope this helps.
@jeffochoa 
Thank u :)
