### ISSUE TITLE
Error viewing documentation in Laravel 7.29

### ISSUE THREAD

**Issue by rbjamaca** [StydeNet/enlighten#50]
**Describe the bug**
When viewing the generated documentation, clicking on an item only displays the error;
BadMethodCallException
Method Illuminate\Database\Eloquent\Collection::chunkWhile does not exist.

maybe because chunkWhile is only available since Laravel 8

**To Reproduce**
1. Use Laravel 7.29 to create a new project
2. Set up enlighten
3. Run phpunit
4. View an item from the generated documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/58159983/106239564-cd310100-623d-11eb-8e5e-2de5fe4fecf7.png)

**Comment by havryliv** [comment]
@rbjamaca Looks like this package supports Laravel 8th and master versions only.

**Comment by jeffochoa** [comment]
@rbjamaca this will be solved in the next release; currently working on the `dev` branch

https://github.com/StydeNet/enlighten/commit/c6dc465d0013a5e9de970c7acf194216bee4d830
