### ISSUE TITLE
Docblocks cannot be parsed correctly because of line endings

### ISSUE THREAD

**Issue by ajcastro** [StydeNet/enlighten#52]
Currently getting the docbloc annotations depends on parsing the string `$docComment` and exploding it in by PHP_EOL. 
This brings an issue when some files are not in correct line endings. Also docblocks like this `/** @enlighten {"order": 4} **/` does not work because the current implementation has `splice(1, -1)`. 

![image](https://user-images.githubusercontent.com/4918318/107721819-8d2b4d00-6d18-11eb-9855-5c4578b66dff.png)

I propose to change it into something like the code below and I think this works better:

```php
   protected static function fromDocComment($docComment)
    {
        $str = \Str::between($docComment, '@enlighten {', '}');

        $decoded = json_decode('{'.$str.'}', true) ?? [];

        return collect([
            'enlighten' => ['include' => true] + $decoded
        ]);
    }
```

**Comment by sileence** [comment]
@ajcastro now you'll be able to have a one line annotation but we're not supporting several annotations on a single line.

I couldn't fix the issue if the test has inconsistent line ending. I think you can fix that with your editor or with git.
