### ISSUE TITLE
Bug when using dataProvider in phpunit

### ISSUE THREAD

**Issue by ajcastro** [StydeNet/enlighten#54]
**Describe the bug**
I have test which uses `@dataProvider`  but it errors in database, I think the `@dataProvider` is not yet considered. 

PhpUnit test:
![image](https://user-images.githubusercontent.com/4918318/110050960-ec1c3900-7d8f-11eb-8a6e-2301b640ce51.png)

Run `phpunit --debug`:
![image](https://user-images.githubusercontent.com/4918318/110050940-dd358680-7d8f-11eb-8988-4ebdd5cdd810.png)

Run `php artisan enlighten --debug`: 
![image](https://user-images.githubusercontent.com/4918318/110051103-32719800-7d90-11eb-85e0-078a58f87199.png)

**Comment by sileence** [comment]
Hi @ajcastro this is ready for next release (you can test the code by pulling dev-main)

We'll add this info in the panel as well.
