### ISSUE TITLE
No Data Is Shown In Generated Documentation on Latest Version Of laravel/framework

### ISSUE THREAD

**Issue by eyounelson** [StydeNet/enlighten#62]
**Describe the bug**
After upgrading laravel/framework to its latest version (8.58as at the time of writing)
 I noticed that my documentation no longer have request and response data in them, just the test's  method title and description (if included with a docblock)

**To Reproduce**
* Run `php artisan enlighten` then look at generated docs and ensure everything is in order
* Upgrade laravel/framework (`composer update` , this should upgrade to the latest version
* Run `php artisan enlighten` again, check the generated docs, you should no longer see request/response data  in your endpoint
* Try downgrading. I have noticed that everything works fine at v8.52 - so run `composer require laravel/framework:8.52`

**Expected behavior**
Response and request data should be available when viewing documentation for an endpoint/method

**Comment by MostafaRabia** [comment]
+1 here

**Comment by emmannl** [comment]
it seems that [this PR](https://github.com/laravel/framework/pull/38372) is the cause of the bug

**Comment by sileence** [comment]
Hi! This issue was fixed in Enlighten 0.7.2. Please upgrade and re-export your views: `php artisan vendor:publish` and tag "enlighten-views".

Thanks for the fix @emmannl and for reporting the issue @MostafaRabia
